config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :courses

  root to: 'courses#index'

  namespace :admin do
    resources :courses

    root to: 'courses#index'
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user, namespace)
    return unless user

    case namespace
    when 'application'
      can :read, Course, users: { id: user.id }
      can :read, Course, user_groups: { user_groups_users: { user_id: user.id } }
    when 'admin'
      can :manage, Course
      can :manage, UserGroup
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  validates :title, presence: true, uniqueness: true

  has_many :courses_users
  has_many :users, through: :courses_users

  has_many :courses_user_groups
  has_many :user_groups, through: :courses_user_groups
end

app/models/courses_user.rb
class CoursesUser < ApplicationRecord
  belongs_to :course
  belongs_to :user
end

app/models/courses_user_group.rb
class CoursesUserGroup < ApplicationRecord
  belongs_to :course
  belongs_to :user_group
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_groups_users
  has_many :user_groups, through: :user_groups_users

  has_many :course_users
  has_many :courses, through: :course_users

  # for example; in real project we will need to use something like permissions model with roles and etc
  def admin?
    id == 1
  end
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  validates :title, presence: true, uniqueness: true

  has_many :user_groups_users
  has_many :users, through: :user_groups_users
end

app/models/user_groups_user.rb
class UserGroupsUser < ApplicationRecord
  belongs_to :user
  belongs_to :user_group
end

app/controllers/admin/courses_controller.rb
class Admin::CoursesController < ApplicationController
  load_and_authorize_resource

  def index
    @courses = @courses.includes(:users, :user_groups)
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    if @course.save
      associate_user_groups

      redirect_to admin_courses_path
    else
      render 'new'
    end
  end

  def update
    if @course.update(course_params)
      associate_user_groups
      associate_users

      redirect_to admin_courses_path
    else
      render 'edit'
    end
  end

  def destroy
    @course.destroy

    redirect_to admin_courses_path
  end

  private

  def course_params
    params.require(:course)
      .permit(:title, :description, user_groups_attributes: [:id, :_destroy])
  end

  def associate_user_groups
    @course.user_groups = []
    params[:course][:user_groups].delete_if(&:blank?).each do |user_group_id|
      @course.user_groups << UserGroup.find(user_group_id)
    end
  end

  def associate_users
    @course.users = []
    params[:course][:users].delete_if(&:blank?).each do |user_id|
      @course.users << User.find(user_id)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper

  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |_exception|
    redirect_to new_user_session_path, alert: I18n.t('cancan.access_denied')
  end

  def current_ability
    @current_ability ||= Ability.new(current_user, current_namespace(need_application: true))
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  load_and_authorize_resource

  def index
  end

  def show
  end
end

app/helpers/admin/courses_helper.rb
module Admin::CoursesHelper
  def user_groups_collection
    UserGroup.order('title')
  end

  def users_collection
    User.order('id')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_namespace(need_application: true)
    namespace = controller_path.split('/').first

    namespace = %w(application admin).include?(namespace) ? namespace : 'application'

    return nil if !need_application && namespace == 'application'

    namespace
  end

  def can_manage_courses?
    current_user.admin? && current_namespace(need_application: true) == 'admin'
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/admin/courses/_form.html.erb
<div class='row'>
  <div class='col-xs-12'>
    <%= simple_form_for [:admin, @course] do |f| %>
      <%= f.input :title %>
      <%= f.input :description %>

      <%= f.input :user_groups, as: :select,
        collection: user_groups_collection,
        selected: f.object.user_groups.pluck(:id),
        label_method: :title,
        value_method: :id,
        input_html: { multiple: true } %>

      <%= f.input :users, as: :select,
        collection: users_collection,
        selected: f.object.users.pluck(:id),
        label_method: :email,
        value_method: :id,
        input_html: { multiple: true } %>

      <%= f.submit class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/admin/courses/edit.html.erb
<%= render partial: 'form' %>

app/views/admin/courses/index.html.erb
<%= render partial: 'shared/courses/index' %>

app/views/admin/courses/new.html.erb
<%= render partial: 'form' %>

app/views/admin/courses/show.html.erb
<div class='row'>
  <div class='col-xs-12'>
    <div class='page-header'>
      <h1><%= @course.title %> <small><%= @course.description %>&nbsp;<%= link_to 'Edit', edit_admin_course_path(@course) %>&nbsp; <%= link_to 'Destroy', admin_course_path(@course), method: :delete, data: { confirm: 'Are u sure?' } %></small></h1>

      <h2>Groups</h2>

      <ul>
        <% if @course.user_groups.present? %>
          <% @course.user_groups.each do |user_group| %>
            <li>
              <%= user_group.title %>
            </li>
          <% end %>
        <% else %>
          <li>
            <p class='text-info'>
              Nothing here
            </p>
          </li>
        <% end %>
      </ul>

      <hr />

      <h2>Users</h2>
      <ul>
        <% if @course.users.present? %>
          <% @course.users.each do |user| %>
            <li>
              <%= user.email %>
            </li>
          <% end %>
        <% else %>
          <li>
            <p class='text-info'>
              Nothing here
            </p>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/courses/index.html.erb
<%= render partial: 'shared/courses/index' %>

app/views/courses/show.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1><%= @course.title %> <small><%= @course.description %></small></h1>

    <%= link_to 'Complete action', '#', class: 'btn btn-success' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EdusonTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class='navbar navbar-default'>
      <div class='container-fluid'>
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class='navbar-header'>
          <button type='button' class='navbar-toggle collapsed' data-toggle='collapse' data-target='#bs-example-navbar-collapse-1' aria-expanded='false'>
            <span class='sr-only'>Toggle navigation</span>
            <span class='icon-bar'></span>
            <span class='icon-bar'></span>
            <span class='icon-bar'></span>
          </button>
          <a class='navbar-brand' href='#'>Brand</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class='collapse navbar-collapse' id='bs-example-navbar-collapse-1'>
          <ul class='nav navbar-nav'>
            <li class='<%= 'active' if current_namespace(need_application: true) == 'application' %>'>
              <%= link_to 'Courses list', courses_path %>
            </li>

            <% if current_user&.admin? %>
              <li class='<%= 'active' if current_namespace(need_application: true) == 'admin' %>'>
                <%= link_to "Admin's courses list", admin_courses_path %>
              </li>
            <% end %>

          </ul>
          <ul class='nav navbar-nav navbar-right'>
            <li class='dropdown'>
              <% if current_user %>
                <a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-haspopup='true' aria-expanded='false'>
                  <%= current_user.email %><span class='caret'></span>
                </a>
                <ul class='dropdown-menu'>
                  <li>
                    <%= link_to 'Exit', destroy_user_session_path, method: :delete %>
                  </li>
                </ul>

              <% else %>
                <%= link_to 'Sign in', new_user_session_path %>
              <% end %>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <div class='container-fluid'>
      <div class='container'>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/shared/courses/_index.html.erb
<div class='row'>
  <div class='col-xs-12'>
    <%= link_to 'New course', new_admin_course_path, class: 'btn btn-primary' if can_manage_courses? %>

    <% if @courses.present? %>
      <table class="table table-responsive">
        <thead>
          <th>Title</th>

          <% if can_manage_courses? %>
            <th>
              Groups
            </th>

            <th>
              Users
            </th>
          <% end %>
        </thead>

        <tbody>
          <% @courses.each do |course| %>
            <tr>
              <td>
                <%= link_to course.title, [current_namespace(need_application: false), course] %>
              </td>

              <% if can_manage_courses? %>
                <td>
                  <%= course.user_groups.pluck(:title).join(', ').presence || 'Nothing here' %>
                </td>
                <td>
                  <%= course.users.pluck(:email).join(', ').presence || 'Nothing here' %>
                </td>
              <% end %>
            </tr>
          <% end %>
        </tbody>

      </table>
    <% else %>
      <p class='text-info'>
        Nothing here :/
      </p>
    <% end %>
  </div>
</div>